# Insert here all the libraries you need
# Format: http://yaml.org/

# Specify here your preferred CRAN miror
miror: http://cran.univ-paris1.fr

# Descending priority
packages:
  # Framework packages
  - R.utils
  - log4r
  - rredis
  - compiler
  - RUnit

  # Your packages
  # - ggplot2
